config/routes.rb
Skyfarm::Application.routes.draw do
  
  match ':controller(/:action(/:id(.:format)))'
  
  match 'enter_tallied_consumption' => 'tallied_consumptions#enter_tallied_consumption'
  match 'save_tallied_consumption' => 'tallied_consumptions#save_tallied_consumption'  
  
  
  
  
  resources :users
  resources :expenses
  resources :tallied_items
  resources :tallied_consumptions
  resources :billing_periods
  resources :payments

  root :to => "info#index"

  
end

app/models/tallied_consumption.rb
class TalliedConsumption < ActiveRecord::Base
  belongs_to :user
  belongs_to :tallied_item
  belongs_to :billing_period
  
  validates_presence_of :user
  validates_presence_of :tallied_item
  
  def to_label
    "#{number} #{tallied_item.name.downcase.pluralize}"
  end
  
  def cost
    tallied_item.price * number
  end
  
end

app/controllers/tallied_consumptions_controller.rb
class TalliedConsumptionsController < ApplicationController
  active_scaffold :tallied_consumptions do |config|
    # Limited column display for usability
    config.columns = [:user, :tallied_item, :number, :cost, :billing_period, :created_at]    

    # Latest first
    config.list.sorting = { :created_at => :desc }

    # Don't allow any changes to DB, just reading
    config.actions = [:list, :show, :search]
  end
  
  # page where you enter how many check marks each person has.
  # this is done once a month by the alcohol person (Joseles).
  # will create a rake task to remind that person.
  def enter_tallied_consumption
    @users = User.active
    @tallied_items = TalliedItem.all
    @counter = 0
  end
  
  def save_tallied_consumption
    redirect_to root_url unless params['tallied_consumptions']
    params['tallied_consumptions'].each do |form_field|
      tallied_consumption = TalliedConsumption.new
      tallied_consumption.number = form_field.last["number"].to_i
      tallied_consumption.user_id = form_field.last["user_id"].to_i
      tallied_consumption.tallied_item_id = form_field.last["tallied_item_id"].to_i
      tallied_consumption.save!
    end
    redirect_to tallied_consumptions_path
  end
  
end

app/helpers/tallied_consumptions_helper.rb
module TalliedConsumptionsHelper
  
  def cost_column(record)
    number_to_currency record.cost
  end
  
end

app/views/tallied_consumptions/enter_tallied_consumption.html.erb
<h3>Enter how much people have consumed.</h3>
You can do this as often as you like, it will add up at the end of the billing period. <br/>
You can edit which items are tracked on <%= link_to "this page", tallied_items_path %>. <br/><br/>

<%= form_tag('/save_tallied_consumption') do -%>
  <table>
    
    <!-- Item headings -->
    <tr>
      <th></th>
      <% @tallied_items.each do |item| %>
        <th><%= item.name %> (<%= number_to_currency item.price %>)</th>
      <% end %>
    </tr>
    
    <!-- Rows for people -->
    <% @users.each do |user| %>
      <tr>
        <th><%= user.short_name %></th>
        
        <!-- Input fields -->
        <% @tallied_items.each do |item| %>
          <td>
            <%= text_field_tag "tallied_consumptions[#{@counter}][number]", 0 %>
            <%= hidden_field_tag "tallied_consumptions[#{@counter}][tallied_item_id]", item.id %>
            <%= hidden_field_tag "tallied_consumptions[#{@counter}][user_id]", user.id %>
            <% @counter += 1 %>
          </td>
        <% end %>
        
      </tr>
    <% end %>
    
  </table>
  <div><%= submit_tag 'Save' %></div>
<% end -%>